import categories_relations_homological_mirror_symmetry_foundation_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace categories_relations_homological_mirror_symmetry_foundation_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end categories_relations_homological_mirror_symmetry_foundation_canonical_lane_mathlib
end HautevilleHouse
